# Generated by Django 3.1.1 on 2020-09-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),  # to pierwsze to nazwa aplikacji tu  'core' a druga to nazwa migracji
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
