# Generated by Django 3.1.1 on 2020-09-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200906_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, choices=[(1, 10), (2, 13), (3, 16), (4, 18)], default=10, null=True),
        ),
    ]
