# Generated by Django 3.1.1 on 2020-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200912_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, choices=[(0, 'kids'), (1, 'kids'), (2, 'kids')], default=2, null=True),
        ),
    ]
